Update 'corrupt' and docstring of InstalledRpms for empty packages (#2650)
* Raise SkipException when no packages are found in installed_rpms

- The spec installed_rpms sometimes collects nothing but the following
  kind of error messages only:
    error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
    error: cannot open Packages database in /var/lib/rpm
- The InstalledRpms should raise SkipException and skip it to avoid
  false positives when need to check packages not installed.

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

* Raise the Exception when applying `in`

- to keep the "corrupt" situation, in case it's useful for some rules

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

* remove unused lines

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

* remove one more unrelated line

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

* Keep the package as empty dict instead of None when db corruption

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>