fix: enhance Uname.fixed_by()
Exception: TypeError: '<' not supported between instances of 'str' and 'int'
is returned when the fixed_by or introduced_in doesn't have distribution part
in release and version and other release parts are the same as current kernel.

The detailed update is not doing comparation the distribution part in release.

Signed-off-by: Ping Qin <piqin@redhat.com>