fix: enhance RpmVPackage handles the rpm error message (#4521)
Enhance the parser RpmVPackage to handle error logs when the rpm -V command fails.

Example：

% cat data/insights_commands/rpm_-V_lvm2

error: rpmdb: BDB0113 Thread/process 2598125/139777000216448 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 - (-30973)

Signed-off-by: Sheng Lao <shlao@redhat.com>
(cherry picked from commit 3965b6ca56e37210d59104a956b1adba1f90a561)