Raise SkipException when no packages are found in installed_rpms
- The spec installed_rpms sometimes collects nothing but the following
  kind of error messages only:
    error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
    error: cannot open Packages database in /var/lib/rpm
- The InstalledRpms should raise SkipException and skip it to avoid
  false positives when need to check packages not installed.

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>