fix: update Uname parser to fix LooseVersion comparision error (#3814)
* fix: enhance Uname.fixed_by()

Exception: TypeError: '<' not supported between instances of 'str' and 'int'
is returned when the fixed_by or introduced_in doesn't have distribution part
in release and version and other release parts are the same as current kernel.

The detailed update is not doing comparation the distribution part in release.

Signed-off-by: Ping Qin <piqin@redhat.com>

* fix: Update Uname.fixed_by()

When _lv_release in self and other both or neither have the distribution
part, compare them directly. Otherwise, removing the distribution part
first, then doing the comparation without the distribution part and
raising a warning.

Signed-off-by: Ping Qin <piqin@redhat.com>

* fix: Add test for pad_release() and warnings in fixed_by()
* fix: seperate the test cases for warnings in a different method

Signed-off-by: Ping Qin <piqin@redhat.com>