fix: py3.9 test error: 'HTTPResponse' object has no attribute 'strict' (#3780)
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>
(cherry picked from commit 282c334d460a5f112bf9880aeffb72e849ba3dd4)