Update specs to rules script to work with version 3 of core (#1192)
* Adding specs_to_rules.py back to insight-core repo

* Changes for core 3.0 cont.

* Continued work on getting specs_to_rules working with Core vesrion 3.x
Changes to spec_fatory to add setting content inner.__doc__ based on spec condig in default.py
Changes to default.py to add docstrings to each defined datasourec in the file.

* Fixed python 3.x issue..
TypeError: sequence item 0 expected str instance, bytes found

* Changes to text (escape special chars) added to doctrings so that
Spihinx would not complain

* Corrected an issue that was causing test failure in test_specs.py

* Flake8 issue and dosctring issue

* Changed 'Command' - to 'Command:' for semid datasource in default.y
Made a function in spec_factory.py to escape special chars for
spec content

(cherry picked from commit d6daea945c47ada40e2d941f451ad59381ae7630)